import Link from "next/link";

export default function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="w-full py-8 mt-auto border-t border-gray-200 bg-white/50 backdrop-blur-sm">
      <div className="container mx-auto px-4 max-w-6xl">
        <div className="flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="text-sm text-gray-500">
            &copy; {currentYear} Teach Anything Now. All rights reserved.
          </div>
          
          <nav className="flex gap-6 text-sm text-gray-600">
            <Link href="/terms" className="hover:text-[#00a884] transition-colors">
              Terms of Service
            </Link>
            <Link href="/privacy" className="hover:text-[#00a884] transition-colors">
              Privacy Policy
            </Link>
          </nav>
        </div>
        
        <div className="mt-4 text-xs text-gray-400 text-center md:text-left max-w-2xl">
          Disclaimer: Content is generated by AI and may contain inaccuracies. 
          Please review all materials before using them in an educational setting.
        </div>
      </div>
    </footer>
  );
}
