import Link from "next/link";

export default function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="w-full py-8 mt-auto border-t border-white/20 bg-transparent">
      <div className="container mx-auto px-4 max-w-6xl">
        <div className="flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="text-sm text-white/90">
            &copy; {currentYear} EduConnect Asia Ltd. All rights reserved.
          </div>
          
          <nav className="flex gap-6 text-sm text-white/90">
            <Link href="/terms" className="hover:text-gray-200 transition-colors">
              Terms of Service
            </Link>
            <Link href="/privacy" className="hover:text-gray-200 transition-colors">
              Privacy Policy
            </Link>
          </nav>
        </div>
        
        <div className="mt-4 text-xs text-white/70 text-center md:text-left max-w-2xl">
          Disclaimer: Content is generated by AI. Please review all materials before using them in an educational setting.
        </div>
      </div>
    </footer>
  );
}
