export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <h1 className="text-3xl font-bold mb-8 text-gray-900 font-handwritten">Terms of Service</h1>
      
      <div className="prose prose-green max-w-none text-gray-700">
        <p className="lead text-xl text-gray-600 mb-8">
          Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-gray-800">1. Introduction</h2>
          <p>
            Welcome to Teach Anything Now (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). By accessing or using our website and services, 
            you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-gray-800">2. AI-Generated Content Disclaimer</h2>
          <p className="font-medium bg-yellow-50 p-4 border-l-4 border-yellow-400 mb-4 rounded-r">
            <strong>Critical Notice:</strong> Our service uses Artificial Intelligence (AI) to generate educational materials. 
            AI can make mistakes, &quot;hallucinate&quot; facts, or produce biased content.
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li>You acknowledge that materials generated by Teach Anything Now are drafts and starting points.</li>
            <li>You are solely responsible for reviewing, verifying, and editing all content for accuracy, safety, and appropriateness before presenting it to students.</li>
            <li>We do not guarantee the accuracy, completeness, or pedagogical value of any generated content.</li>
            <li>We serve as a tool for educators, not a replacement for professional judgment.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-gray-800">3. User Accounts and Payments</h2>
          <p>
            You may need to create an account to access certain features. You are responsible for maintaining the confidentiality of your account.
          </p>
          <p className="mt-4">
            <strong>Payments:</strong> We use Stripe for payment processing. All payments are final. 
            Due to the immediate costs of AI generation, we generally do not offer refunds once content generation has started, 
            except where required by law or in cases of technical failure on our end.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-gray-800">4. Intellectual Property</h2>
          <p>
            <strong>Your Content:</strong> You retain ownership of the input topics you provide.
          </p>
          <p className="mt-2">
            <strong>Generated Materials:</strong> Upon successful payment and generation, we grant you a perpetual, 
            non-exclusive, royalty-free license to use, modify, distribute, and display the generated PowerPoint slides, 
            worksheets, and audio files for your personal, educational, and professional use.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-gray-800">5. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Teach Anything Now shall not be liable for any indirect, incidental, 
            special, consequential, or punitive damages, including but not limited to loss of profits, data, or goodwill, 
            arising out of or in connection with your use of our service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4 text-gray-800">6. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the service constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-gray-800">7. Contact</h2>
          <p>
            If you have any questions about these Terms, please contact us via the feedback form on our website.
          </p>
        </section>
      </div>
    </div>
  );
}
