"use client";

import { useRouter } from "next/navigation";
import { useSession } from "next-auth/react";
import { useEffect } from "react";

export default function LandingPage() {
  const router = useRouter();
  const { data: session, status } = useSession();

  useEffect(() => {
    if (status === "authenticated") {
      router.push("/");
    }
  }, [status, router]);

  if (status === "loading") {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[var(--background)]">
        <div className="w-8 h-8 border-2 border-[var(--primary)] border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[var(--background)]">
      {/* Header */}
      <header className="bg-[var(--surface)] border-b border-[var(--border)]">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-[var(--primary)] rounded-lg flex items-center justify-center">
              <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
              </svg>
            </div>
            <span className="text-lg font-semibold text-[var(--text-primary)]">Teach Anything</span>
          </div>
          <button
            onClick={() => router.push("/auth/signin")}
            className="text-[var(--primary)] font-medium hover:underline"
          >
            Sign in
          </button>
        </div>
      </header>

      {/* Hero */}
      <section className="bg-[var(--surface)]">
        <div className="max-w-6xl mx-auto px-6 py-20 md:py-28">
          <div className="max-w-2xl">
            <h1 className="text-4xl md:text-5xl font-bold text-[var(--text-primary)] mb-6 leading-tight">
              Create complete lesson materials in seconds
            </h1>
            <p className="text-lg text-[var(--text-secondary)] mb-8">
              Enter any topic. Get a PowerPoint, podcast audio, worksheet, and answer sheet — instantly generated by AI.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <button
                onClick={() => router.push("/auth/signin")}
                className="btn btn-primary text-base px-8 py-3"
              >
                Get started
              </button>
              <div className="flex items-center gap-2 text-[var(--text-secondary)]">
                <span className="text-2xl font-bold text-[var(--text-primary)]">£1</span>
                <span>per lesson package</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-16 md:py-24">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-2xl font-bold text-[var(--text-primary)] mb-12 text-center">
            Everything you need to teach any topic
          </h2>
          
          <div className="grid md:grid-cols-2 gap-6">
            <div className="card p-6">
              <div className="w-10 h-10 bg-[var(--primary)] bg-opacity-10 rounded-lg flex items-center justify-center mb-4">
                <svg className="w-5 h-5 text-[var(--primary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
                </svg>
              </div>
              <h3 className="text-lg font-semibold text-[var(--text-primary)] mb-2">PowerPoint Slides</h3>
              <p className="text-[var(--text-secondary)]">
                Professional presentation with clear structure and key points
              </p>
            </div>

            <div className="card p-6">
              <div className="w-10 h-10 bg-[var(--primary)] bg-opacity-10 rounded-lg flex items-center justify-center mb-4">
                <svg className="w-5 h-5 text-[var(--primary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.536 8.464a5 5 0 010 7.072m2.828-9.9a9 9 0 010 12.728M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" />
                </svg>
              </div>
              <h3 className="text-lg font-semibold text-[var(--text-primary)] mb-2">Podcast Audio</h3>
              <p className="text-[var(--text-secondary)]">
                Natural-sounding audio explanation for auditory learners
              </p>
            </div>

            <div className="card p-6">
              <div className="w-10 h-10 bg-[var(--primary)] bg-opacity-10 rounded-lg flex items-center justify-center mb-4">
                <svg className="w-5 h-5 text-[var(--primary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
              </div>
              <h3 className="text-lg font-semibold text-[var(--text-primary)] mb-2">Student Worksheet</h3>
              <p className="text-[var(--text-secondary)]">
                Exercises and questions to reinforce understanding
              </p>
            </div>

            <div className="card p-6">
              <div className="w-10 h-10 bg-[var(--primary)] bg-opacity-10 rounded-lg flex items-center justify-center mb-4">
                <svg className="w-5 h-5 text-[var(--primary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <h3 className="text-lg font-semibold text-[var(--text-primary)] mb-2">Answer Key</h3>
              <p className="text-[var(--text-secondary)]">
                Complete answers for quick and easy grading
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="bg-[var(--surface)] py-16 md:py-24">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-2xl font-bold text-[var(--text-primary)] mb-12 text-center">
            Three simple steps
          </h2>
          
          <div className="grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            <div className="text-center">
              <div className="w-12 h-12 bg-[var(--primary)] text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                1
              </div>
              <h3 className="font-semibold text-[var(--text-primary)] mb-2">Enter your topic</h3>
              <p className="text-[var(--text-secondary)] text-sm">
                Type any subject you want to teach
              </p>
            </div>

            <div className="text-center">
              <div className="w-12 h-12 bg-[var(--primary)] text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                2
              </div>
              <h3 className="font-semibold text-[var(--text-primary)] mb-2">Pay £1</h3>
              <p className="text-[var(--text-secondary)] text-sm">
                Secure payment via Stripe
              </p>
            </div>

            <div className="text-center">
              <div className="w-12 h-12 bg-[var(--primary)] text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                3
              </div>
              <h3 className="font-semibold text-[var(--text-primary)] mb-2">Download files</h3>
              <p className="text-[var(--text-secondary)] text-sm">
                Get all four materials instantly
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 md:py-24">
        <div className="max-w-6xl mx-auto px-6">
          <div className="card p-8 md:p-12 text-center">
            <h2 className="text-2xl md:text-3xl font-bold text-[var(--text-primary)] mb-4">
              Ready to save hours of preparation?
            </h2>
            <p className="text-[var(--text-secondary)] mb-8 max-w-lg mx-auto">
              Join educators who create professional lesson materials in seconds, not hours.
            </p>
            <button
              onClick={() => router.push("/auth/signin")}
              className="btn btn-primary text-base px-8 py-3"
            >
              Start creating
            </button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-[var(--border)] py-8">
        <div className="max-w-6xl mx-auto px-6 text-center text-[var(--text-muted)] text-sm">
          <p>Teach Anything Now</p>
        </div>
      </footer>
    </div>
  );
}
