"use client";

import { useRouter } from "next/navigation";
import { useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";

interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  author: string;
  tags: string[];
  created_at: string;
}

export default function LandingPage() {
  const router = useRouter();
  const { data: session, status } = useSession();
  const [featuredPosts, setFeaturedPosts] = useState<BlogPost[]>([]);

  useEffect(() => {
    if (status === "authenticated") {
      router.push("/");
    }
    // Fetch featured blog posts for SEO
    fetchFeaturedPosts();
  }, [status, router]);

  const fetchFeaturedPosts = async () => {
    try {
      const response = await fetch("/api/blog?featured=true&limit=3");
      if (response.ok) {
        const data = await response.json();
        setFeaturedPosts(data.posts || []);
      }
    } catch (error) {
      console.error("Error fetching featured posts:", error);
    }
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString("en-GB", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  };

  if (status === "loading") {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[var(--background)]">
        <div className="w-8 h-8 border-2 border-[var(--primary)] border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[var(--background)]">
      {/* Header */}
      <header className="bg-[var(--surface)] border-b border-[var(--border)]">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          {/* Logo */}
          <div className="flex items-center gap-2">
            <Image 
              src="/logo.png" 
              alt="Teach Anything Logo" 
              width={32}
              height={32}
              priority
            />
            <span className="text-lg font-semibold text-[var(--text-primary)]">Teach Anything Now</span>
          </div>

          {/* Navigation */}
          <div className="flex items-center gap-6">
            <Link
              href="/blog"
              className="text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)] hidden sm:block"
            >
              Blog
            </Link>
            <button
              onClick={() => router.push("/auth/signin")}
              className="btn btn-primary"
            >
              Get started
            </button>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="bg-[var(--surface)]">
        <div className="max-w-7xl mx-auto px-6 py-16 md:py-24">
          <div className="grid lg:grid-cols-2 gap-12 items-start">
            {/* Left Column - Hero Content */}
            <div className="max-w-xl">
              <h1 className="hero-title text-5xl md:text-6xl text-[var(--text-primary)] mb-6">
                Create high quality lesson materials in seconds
              </h1>
              <p className="text-lg text-[var(--text-secondary)] mb-8 leading-relaxed">
                Enter any topic. Get a PowerPoint, podcast audio, editable worksheets with answer keys, and high-quality images — instantly generated by AI.
              </p>
              <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4">
                <button
                  onClick={() => router.push("/auth/signin")}
                  className="btn btn-primary"
                >
                  Get started
                </button>
                <div className="flex items-center gap-2">
                  <span className="text-3xl font-bold text-[var(--text-primary)]">£1</span>
                  <span className="text-[var(--text-secondary)]">per lesson package</span>
                </div>
              </div>
            </div>

            {/* Right Column - Features Grid */}
            <div>
              <h2 className="text-3xl font-bold text-[var(--text-primary)] mb-8">
                Complete AI-powered teaching package
              </h2>
              
              {/* Features Grid */}
              <div className="grid grid-cols-2 gap-4" role="list" aria-label="Teaching materials included">
                {/* PowerPoint Slides */}
                <article className="card p-6 border border-[var(--border)]" role="listitem">
                  <div className="w-12 h-12 bg-[var(--primary)] rounded-xl flex items-center justify-center mb-4" aria-hidden="true">
                    <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-label="Presentation icon">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
                    </svg>
                  </div>
                  <h3 className="text-lg font-bold text-[var(--text-primary)] mb-2">AI PowerPoint Generator</h3>
                  <p className="text-sm text-[var(--text-secondary)]">
                    Professional presentation slides with clear structure and key teaching points
                  </p>
                </article>

                {/* Worksheets & Answer Key */}
                <article className="card p-6 border border-[var(--border)]" role="listitem">
                  <div className="w-12 h-12 bg-[var(--primary)] rounded-xl flex items-center justify-center mb-4" aria-hidden="true">
                    <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-label="Worksheet icon">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                  </div>
                  <h3 className="text-lg font-bold text-[var(--text-primary)] mb-2">Worksheets & Answer Key</h3>
                  <p className="text-sm text-[var(--text-secondary)]">
                    Editable DOCX worksheets with complete answer keys for quick grading
                  </p>
                </article>

                {/* AI Images */}
                <article className="card p-6 border border-[var(--border)]" role="listitem">
                  <div className="w-12 h-12 bg-[var(--primary)] rounded-xl flex items-center justify-center mb-4" aria-hidden="true">
                    <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-label="Image icon">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                    </svg>
                  </div>
                  <h3 className="text-lg font-bold text-[var(--text-primary)] mb-2">Relevant Images</h3>
                  <p className="text-sm text-[var(--text-secondary)]">
                    High-quality educational images and illustrations for your presentations
                  </p>
                </article>

                {/* Podcast Audio */}
                <article className="card p-6 border border-[var(--border)]" role="listitem">
                  <div className="w-12 h-12 bg-[var(--primary)] rounded-xl flex items-center justify-center mb-4" aria-hidden="true">
                    <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-label="Audio icon">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.536 8.464a5 5 0 010 7.072m2.828-9.9a9 9 0 010 12.728M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" />
                    </svg>
                  </div>
                  <h3 className="text-lg font-bold text-[var(--text-primary)] mb-2">Podcast-Style Audio</h3>
                  <p className="text-sm text-[var(--text-secondary)]">
                    Audio explanations for independent study and accessibility. Perfect for podcast-style learning.
                  </p>
                </article>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-16 md:py-20 bg-[var(--background)]">
        <div className="max-w-4xl mx-auto px-6">
          <h2 className="text-3xl md:text-4xl font-bold text-[var(--text-primary)] mb-4 text-center">
            How It Works
          </h2>
          <p className="text-lg text-[var(--text-secondary)] mb-12 text-center max-w-2xl mx-auto">
            AI-powered lesson planning made simple for busy teachers
          </p>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="w-16 h-16 bg-[var(--primary)] rounded-2xl flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl font-bold text-white">1</span>
              </div>
              <h3 className="text-lg font-bold text-[var(--text-primary)] mb-2">
                Enter Your Topic
              </h3>
              <p className="text-[var(--text-secondary)]">
                Type any subject or lesson topic you want to teach
              </p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-[var(--primary)] rounded-2xl flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl font-bold text-white">2</span>
              </div>
              <h3 className="text-lg font-bold text-[var(--text-primary)] mb-2">
                AI Generates Materials
              </h3>
              <p className="text-[var(--text-secondary)]">
                Our AI creates presentations, worksheets, audio, and images in 30-60 seconds
              </p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-[var(--primary)] rounded-2xl flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl font-bold text-white">3</span>
              </div>
              <h3 className="text-lg font-bold text-[var(--text-primary)] mb-2">
                Download & Teach
              </h3>
              <p className="text-[var(--text-secondary)]">
                Get all files instantly and start teaching right away
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 md:py-24 bg-[var(--surface)]">
        <div className="max-w-4xl mx-auto px-6">
          <div className="card border border-[var(--border)] rounded-3xl p-8 md:p-12 text-center">
            <h2 className="text-3xl md:text-4xl font-bold text-[var(--text-primary)] mb-4">
              Ready to save hours of preparation time?
            </h2>
            <p className="text-lg text-[var(--text-secondary)] mb-8 max-w-2xl mx-auto">
              Join teachers worldwide who use AI to create professional lesson materials in seconds, not hours.
            </p>
            <button
              onClick={() => router.push("/auth/signin")}
              className="btn btn-primary text-lg"
            >
              Start creating for £1
            </button>
            <p className="text-sm text-[var(--text-muted)] mt-4">
              No subscription. Pay only when you generate content.
            </p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-[var(--border)] py-8 bg-[var(--surface)]">
        <div className="max-w-7xl mx-auto px-6">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <p className="text-[var(--text-muted)] text-sm">
              © 2025 Teach Anything Now. All rights reserved.
            </p>
            <Link
              href="/blog"
              className="text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)]"
            >
              Blog
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
